# Generated by Django 4.0.5 on 2022-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('item_code', models.CharField(max_length=3)),
                ('kind_code', models.CharField(max_length=2)),
                ('item_name', models.TextField()),
                ('kind_name', models.TextField()),
            ],
        ),
    ]
